In [29]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [30]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [31]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [32]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [33]:
#from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
22 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.71968812 0.59073074 0.69147619 0.66657526
        nan        nan 0.63881268 0.63832888 0.6712105  0.645904
        nan        nan 0.66990505 0.63585571 0.63967923 0.66249091
        nan        nan 0.69168088 0.66357206 0.67809977 0.63991321]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [35]:
re=grid.cv_results_
rscore=grid.best_params_
print(f"The R_score value for best parameter:{rscore}")

The R_score value for best parameter:{'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}

In [36]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002350,0.000331,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002186,0.000612,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.009037,0.000914,0.004155,0.000191,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.748434,0.697754,0.745285,0.669786,0.737181,0.719688,0.030851,1
3,0.006160,0.000557,0.004208,0.000342,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.649918,0.548159,0.618781,0.573821,0.562974,0.590731,0.037838,16
4,0.008171,0.000757,0.004433,0.000423,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.709063,0.608194,0.745055,0.703458,0.691611,0.691476,0.045298,3
5,0.006527,0.000588,0.004055,0.000512,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.660121,0.549557,0.652063,0.743753,0.727383,0.666575,0.068701,7
6,0.001632,0.000729,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001358,0.000206,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.007837,0.000547,0.003922,0.000425,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.801450,0.594750,0.392529,0.731839,0.673496,0.638813,0.140645,13
9,0.007233,0.000731,0.004276,0.000548,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.660765,0.586638,0.656305,0.590171,0.697765,0.638329,0.043244,14
10,0.007744,0.000469,0.003555,0.000220,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.720823,0.488830,0.740977,0.662346,0.743077,0.671210,0.095744,5
11,0.008458,0.001167,0.004124,0.000432,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.630554,0.566995,0.641784,0.680943,0.709245,0.645904,0.048413,10
12,0.001781,0.000351,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001687,0.000622,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.027870,0.002522,0.003392,0.000271,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.740379,0.466426,0.734764,0.739794,0.668162,0.669905,0.105323,6
15,0.021262,0.000928,0.003874,0.000487,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.644843,0.487789,0.686834,0.636113,0.723700,0.635856,0.080399,15
16,0.026537,0.001651,0.003550,0.000728,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.722689,0.505149,0.568568,0.668704,0.733286,0.639679,0.089051,12
17,0.024191,0.002842,0.003412,0.000142,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.677740,0.606797,0.721060,0.643149,0.663709,0.662491,0.037790,9
18,0.001084,0.000164,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001355,0.000356,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.007872,0.000489,0.003927,0.000784,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.718957,0.610497,0.746674,0.651847,0.730431,0.691681,0.051860,2
21,0.006681,0.000988,0.003437,0.000476,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.749647,0.450574,0.782338,0.672051,0.663250,0.663572,0.115719,8
22,0.008330,0.000922,0.004161,0.000413,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.711407,0.577472,0.713070,0.639315,0.749235,0.678100,0.061681,4
23,0.006443,0.000750,0.003147,0.000325,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.636901,0.529286,0.721036,0.711911,0.600432,0.639913,0.071513,11